/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trainesi;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import trainesi.DataManager;



/**
 *
 * @author nadaa
 */
public class CarteReductionRemplir extends javax.swing.JFrame {

    /**
     * Creates new form carte_reduction
     */
    int trajet_id;
    int classe;
    public CarteReductionRemplir(int idcarte, int classe) {
        initComponents();
        this.trajet_id =idcarte;
        this.classe =classe;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        idCarte = new javax.swing.JTextField();
        Type_carte = new javax.swing.JComboBox<>();
        az = new javax.swing.JLabel();
        ae = new javax.swing.JLabel();
        continuer = new javax.swing.JButton();
        Retour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Carte de Réduction");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        idCarte.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        idCarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCarteActionPerformed(evt);
            }
        });

        Type_carte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carte étudiant", "Fondation M6", "Fondation H2", "Carte jeune", "Carte d'abonnement" }));
        Type_carte.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Type_carteItemStateChanged(evt);
            }
        });
        Type_carte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Type_carteActionPerformed(evt);
            }
        });

        az.setBackground(new java.awt.Color(51, 51, 51));
        az.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        az.setForeground(new java.awt.Color(255, 255, 255));
        az.setText("ID de la carte");

        ae.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        ae.setForeground(new java.awt.Color(255, 255, 255));
        ae.setText("Type de la carte");

        continuer.setText("Continuer");
        continuer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continuerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                continuerMousePressed(evt);
            }
        });
        continuer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuerActionPerformed(evt);
            }
        });

        Retour.setText("Retour");
        Retour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RetourMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ae, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Type_carte, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(az, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idCarte, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(continuer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(az)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idCarte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ae)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Type_carte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continuer)
                    .addComponent(Retour))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Type_carteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Type_carteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Type_carteActionPerformed

    private void Type_carteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Type_carteItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_Type_carteItemStateChanged

    private void idCarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCarteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCarteActionPerformed

    private void continuerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continuerMouseClicked
      // Obtenez les valeurs des champs
    String idCarteValue = idCarte.getText();
    String typeCarteValue = Type_carte.getSelectedItem().toString();
    //Date dateExpirationValue = date_expiration.getDate();
        

    // Validez si les champs sont remplis
    if (idCarteValue.isEmpty() || typeCarteValue.isEmpty() /*|| dateExpirationValue== null*/ ) {
        JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs.");
        return;
    }

    try {
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/esitraindb", "root", "");
    PreparedStatement validationQuery = con.prepareStatement("SELECT * FROM carte_reduction WHERE idcarte=? AND type_carte=? ");

    // Assurez-vous de remplacer les types de données appropriés en fonction de votre base de données
    validationQuery.setString(1, idCarte.getText());
    validationQuery.setString(2, Type_carte.getSelectedItem().toString());
    ResultSet result = validationQuery.executeQuery();

    if (result.next()) {
        //Date du Voyage
        String query1 = "SELECT DateTbl FROM trajettable WHERE TrajetIdTbl = ?";
        PreparedStatement preparedStatement = con.prepareStatement(query1);
        preparedStatement.setInt(1,trajet_id ); // Assuming trajetId is a String

        ResultSet ResultTripDate = preparedStatement.executeQuery();
        Date date = null;
        if (ResultTripDate.next()) {
            date = ResultTripDate.getDate("DateTbl");
        }
        //Date d'expiration
        String query2 ="SELECT date_expiration FROM carte_reduction WHERE idCarte=? AND Type_carte=? ";
        PreparedStatement ExpirationDate = con.prepareStatement(query2);
        ExpirationDate.setString(1, idCarte.getText());
        ExpirationDate.setString(2, Type_carte.getSelectedItem().toString());
        ResultSet resultExpirationDate = ExpirationDate.executeQuery();
        Date Expirationdate =null;
        if (resultExpirationDate.next()) {
            Expirationdate = resultExpirationDate.getDate("date_expiration");
        }
        
        //Comparer les deux dates :
        if (date != null && Expirationdate != null) {
        if (date.compareTo(Expirationdate) > 0) {
            JOptionPane.showMessageDialog(null, "La carte est valide!");
            int numero_carte =Integer.valueOf(idCarte.getText());
            new RecapPaiment(trajet_id , classe , numero_carte ).setVisible(true); //must take two arguments (idtrajet , id carteReduction) 
            this.dispose();
            
        } else {
            System.out.println("The card is expired.");
            JOptionPane.showMessageDialog(this, "Votre carte est expirée");
            new CarteReductionCheck(trajet_id , classe).setVisible(true);
            this.dispose();

        }
        } else {
            JOptionPane.showMessageDialog(null, "L'une des deux date est vide ");
            
        }

    } else {
        JOptionPane.showMessageDialog(this, "Informations incorrectes. Vérifiez les détails de la carte.");
    }

}  catch (Exception e) {
    JTextArea textArea = new JTextArea(e.toString());
                JScrollPane scrollPane = new JScrollPane(textArea);
                scrollPane.setPreferredSize(new Dimension(400, 200));

                // This what enables text area to be selectable and copyable
                textArea.setEditable(false);
                textArea.setLineWrap(true);
                textArea.setWrapStyleWord(true);

                // Show the dialog with the error message
                JOptionPane.showMessageDialog(this, scrollPane, "Error in continuerMouseClicked function", JOptionPane.ERROR_MESSAGE);
}

            
    }//GEN-LAST:event_continuerMouseClicked
    private DataManager dataManager;
    private void continuerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continuerMousePressed
        // TODO add your handling code here:
        String idCarteValue = idCarte.getText(); // Remplacez avec le champ réel du formulaire
    
    // Créer une instance de DataManager si elle n'existe pas encore
    if (dataManager == null) {
        dataManager = DataManager.getInstance();
    }

    // Stocker les données dans le DataManager
    dataManager.setidCarte(idCarteValue);
    }//GEN-LAST:event_continuerMousePressed

    private void continuerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuerActionPerformed
        // TODO add your handling code here:
        // Récupérer les données du formulaire
        

        
    }//GEN-LAST:event_continuerActionPerformed

    private void RetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetourMouseClicked
        new CarteReductionCheck(trajet_id , classe).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RetourMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Retour;
    private javax.swing.JComboBox<String> Type_carte;
    private javax.swing.JLabel ae;
    private javax.swing.JLabel az;
    private javax.swing.JButton continuer;
    private javax.swing.JTextField idCarte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
