/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trainesi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class RecapPaiment extends javax.swing.JFrame {

    /**
     * Creates new form RecapPaiment
     */
    int trajet_id;
    int classe;
    int carte_id;
    
    Connection Con = null;
    java.sql.PreparedStatement pst = null;
    ResultSet Rs = null , Rs1 = null;
    Statement St = null , St1 = null;
          
    public RecapPaiment(int trajet_id , int classe, int carte_id)  {
        initComponents();
        this.trajet_id =trajet_id;
        this.classe = classe;
        this.carte_id = carte_id;
        afficherTrajet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        Valider = new javax.swing.JButton();
        Valider1 = new javax.swing.JButton();
        Origine = new javax.swing.JTextField();
        Destination = new javax.swing.JTextField();
        Date = new javax.swing.JTextField();
        HeureDepart = new javax.swing.JTextField();
        HeureArrive = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        PrixInitial = new javax.swing.JTextField();
        PrixFinal = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setText("Carte de Reduction");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(9, 220, 220));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel2.setText("Recapitulatif du ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 23, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel3.setText("Paiment ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 72, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel27.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel27.setText("Origine :");

        jLabel29.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel29.setText("Destination :");

        jLabel30.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel30.setText("Date :");

        jLabel31.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel31.setText("HeureDepart :");

        jLabel32.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel32.setText("Heure d'arrivée :");

        jLabel34.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel34.setText("Carte de reduction :");

        jLabel35.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel35.setText("Prix initiale :");

        jLabel36.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel36.setText("Prix final :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)))
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addComponent(jLabel31)
                .addGap(22, 22, 22)
                .addComponent(jLabel32)
                .addGap(26, 26, 26)
                .addComponent(jLabel34)
                .addGap(32, 32, 32)
                .addComponent(jLabel35)
                .addGap(30, 30, 30)
                .addComponent(jLabel36)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 130, 202, -1));

        Valider.setText("ANNULER");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        getContentPane().add(Valider, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 130, 50));

        Valider1.setText("VALIDER");
        getContentPane().add(Valider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 130, 50));
        getContentPane().add(Origine, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 71, -1));
        getContentPane().add(Destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 71, -1));
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 71, -1));
        getContentPane().add(HeureDepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 71, -1));
        getContentPane().add(HeureArrive, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 71, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 71, -1));
        getContentPane().add(PrixInitial, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 71, -1));
        getContentPane().add(PrixFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 71, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValiderActionPerformed
     private void afficherTrajet() {
        try {
            
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/esitraindb", "root", "");
        Statement st = con.createStatement();
        String query = "SELECT OrigineTbl, DestinationTbl, DateTbl, HeureDepart, HeureArrive FROM trajettable WHERE TrajetId=" + trajet_id;
        ResultSet rs = st.executeQuery(query);
        if (rs.next()) {
            Origine.setText("hello");
            Destination.setText(rs.getString("DestinationTbl"));
            Date.setText(rs.getDate("DateTbl").toString());
            HeureDepart.setText(rs.getTime("HeureDepart").toString());
            HeureArrive.setText(rs.getTime("HeureArrive").toString());

            PrixInitial.setText(""); // You seem to be missing the correct value here
            PrixFinal.setText(""); // You seem to be missing the correct value here
        }
    } catch (Exception e) {
        e.printStackTrace(); // It's advisable to print or log the exception for debugging purposes.
    }

            
            
            
         
     }
    /**
     * @param args the command line arguments
     */
   
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Date;
    private javax.swing.JTextField Destination;
    private javax.swing.JTextField HeureArrive;
    private javax.swing.JTextField HeureDepart;
    private javax.swing.JTextField Origine;
    private javax.swing.JTextField PrixFinal;
    private javax.swing.JTextField PrixInitial;
    private javax.swing.JButton Valider;
    private javax.swing.JButton Valider1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
