/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trainesi;

import java.awt.Dimension;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import java.text.ParseException;
import trainesi.AdminLogIn;
import trainesi.AdminOrUser;
/**
 *
 * @author Dell
 */
public class UserConsultationHoraire extends javax.swing.JFrame {

    /**
     * Creates new form ConsultationHoraire
     */
    public UserConsultationHoraire() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Origine = new javax.swing.JComboBox<>();
        Destination = new javax.swing.JComboBox<>();
        GtSearchBTN = new javax.swing.JButton();
        GtRetablirBTN = new javax.swing.JButton();
        GtRetourBTN = new javax.swing.JButton();
        PaimentBTN = new javax.swing.JButton();
        Date = new com.toedter.calendar.JDateChooser();
        Classe = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consultationTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Consultation horaire");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 264, 41));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Origine");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 128, 42));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Destination");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 115, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Classe");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 128, -1));

        Origine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kenitra", "Rabat", "Fes", "Casa", "Marrakesh" }));
        getContentPane().add(Origine, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 125, 86, 33));

        Destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kenitra", "Rabat", "Fes", "Casa", "Marrakesh" }));
        getContentPane().add(Destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 125, 102, 33));

        GtSearchBTN.setText("Search");
        GtSearchBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GtSearchBTNMouseClicked(evt);
            }
        });
        GtSearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GtSearchBTNActionPerformed(evt);
            }
        });
        getContentPane().add(GtSearchBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 199, 145, 50));

        GtRetablirBTN.setText("Rétablir");
        GtRetablirBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GtRetablirBTNMouseClicked(evt);
            }
        });
        GtRetablirBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GtRetablirBTNActionPerformed(evt);
            }
        });
        getContentPane().add(GtRetablirBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 155, 50));

        GtRetourBTN.setText("Retour");
        GtRetourBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GtRetourBTNMouseClicked(evt);
            }
        });
        GtRetourBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GtRetourBTNActionPerformed(evt);
            }
        });
        getContentPane().add(GtRetourBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 144, 40));

        PaimentBTN.setText("Procéder au paiement");
        PaimentBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaimentBTNMouseClicked(evt);
            }
        });
        PaimentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaimentBTNActionPerformed(evt);
            }
        });
        getContentPane().add(PaimentBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 155, 40));
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 125, 170, 33));

        Classe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "1" }));
        getContentPane().add(Classe, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 90, 33));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 128, -1));

        consultationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        consultationTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultationTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(consultationTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 330, 710, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GtSearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GtSearchBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GtSearchBTNActionPerformed

    private void GtRetablirBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GtRetablirBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GtRetablirBTNActionPerformed

    private void GtRetourBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GtRetourBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GtRetourBTNActionPerformed

    private void GtRetourBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GtRetourBTNMouseClicked
        new AdminOrUser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GtRetourBTNMouseClicked
    Connection con=null;
    Statement st=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
 

    private void GtSearchBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GtSearchBTNMouseClicked
        if(Origine.getSelectedIndex()==-1 || Destination.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this,"missing information");
        }else if(Origine.getSelectedItem()==Destination.getSelectedItem()){
            JOptionPane.showMessageDialog(this,"information invalide");
        }
        else{
            try{
               con = DriverManager.getConnection("jdbc:mysql://localhost:3306/esitraindb", "root" , "");
               st = con.createStatement();
               SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                 String formattedDate = sdf.format(Date.getDate());
                 
                 String PDCi ="PlaceDisponibleClasse" + Classe.getSelectedItem().toString()+"Tbl";
                rs = st.executeQuery("SELECT * FROM trajettable WHERE OrigineTbl='" + Origine.getSelectedItem().toString() + "' AND DestinationTbl='" + Destination.getSelectedItem().toString() + "' AND DateTbl='" + formattedDate + "'AND "+PDCi+" > 0");
                //Taking rows from Rs and displaying it to the table 
               if (!rs.next()) {
                    // ResultSet is empty
                    JOptionPane.showMessageDialog(this, "trajet inexistant");
                } else {
                    DefaultTableModel model = new DefaultTableModel();
                    consultationTable.setModel(model);
                    ResultSetMetaData rsmd = rs.getMetaData();
                    int columnCount = rsmd.getColumnCount();

                    // Add column names to the model
                    for (int i = 1; i <= columnCount - 1; i++) {
                        model.addColumn(rsmd.getColumnName(i));
                    }

                    // Add data rows to the model
                    do {
                        Object[] row = new Object[columnCount];
                        for (int i = 1; i <= columnCount; i++) {
                            row[i - 1] = rs.getObject(i);
                        }
                        model.addRow(row);
                    } while (rs.next()); // Use do-while loop to process the current row before moving to the next one
                }
                
            }
            catch (Exception e) {
                        JOptionPane.showMessageDialog(this,e);
    }


            }
    }//GEN-LAST:event_GtSearchBTNMouseClicked

    private void GtRetablirBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GtRetablirBTNMouseClicked
        new UserConsultationHoraire().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GtRetablirBTNMouseClicked
    
    int id ;
    int classe ;
    private void PaimentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaimentBTNActionPerformed
        
    }//GEN-LAST:event_PaimentBTNActionPerformed
    private void PaimentBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaimentBTNMouseClicked
        new CarteReductionCheck(id , classe).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PaimentBTNMouseClicked
  
    private void consultationTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultationTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)consultationTable.getModel();
        int MyIndex = consultationTable.getSelectedRow();
        id  = Integer.valueOf(model.getValueAt(MyIndex , 0).toString()); 
    }//GEN-LAST:event_consultationTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserConsultationHoraire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserConsultationHoraire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserConsultationHoraire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserConsultationHoraire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               UserConsultationHoraire cons1 = new UserConsultationHoraire();
               cons1.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Classe;
    private com.toedter.calendar.JDateChooser Date;
    private javax.swing.JComboBox<String> Destination;
    private javax.swing.JButton GtRetablirBTN;
    private javax.swing.JButton GtRetourBTN;
    private javax.swing.JButton GtSearchBTN;
    private javax.swing.JComboBox<String> Origine;
    private javax.swing.JButton PaimentBTN;
    private javax.swing.JTable consultationTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
